### ISSUE TITLE
How to scan with ZXing and MLKit at the same time?

### ISSUE THREAD

**Issue by randauto** [maulikhirani/scannerX#9]
Hi, I very like your repo, I have an idea, could you make an example about scan barcode, qrcode with zxing and mlkit run parallel.
Result scanned return from mlkit or zxing if one of them is faster.
Thanks in advanced!

**Comment by maulikhirani** [comment]
Interesting!
Thanks for the suggestion, will see if we can do that.

**Comment by randauto** [comment]
I will try to do it, if I get the result I will talk to you.

**Comment by randauto** [comment]
It's really hard, I tried with 2 threads but it seems that the performance is not good, the IO stream processing makes the camera jerky, and laggy (or maybe I'm implementing it the wrong way). I will close this issue and consider this as an idea, hopefully, someone will see and implement this direction or some other way to increase QR code recognition.
